### ISSUE TITLE
Roadway Manager: identify overlapping links

### ISSUE THREAD

**Issue by dkyleward** [Triangle-Modeling-and-Analytics/TRMG2#230]
An enhancement suggested by mike was to identify where the project manager had to choose between competing projects. The "UpdatedWithP" field that already exists is half the solution: it tells you what project was chosen. It doesn't tell you the manager had to choose between two projects both listed in the project list csv file.

I will add a second field to the output scenario network: "Overlap" that will be marked with a 1 if multiple projects were included in the project list csv that were both on the link.

**Comment by Si-Shi** [comment]
@dkyleward Please update us on the status of this. Is it something we can accomplish in FY24?

**Comment by dkyleward** [comment]
Haven't done it, but with the refactoring of the project manager complete, I don't think this will be too hard. We could do it in FY 24.

**Comment by dkyleward** [comment]
Done. Now "UpdatedWithP" is followed by the "Overlap" field, which will contain a 1 for links that had projects overlap.
