### ISSUE TITLE
Add 2050 Toll Road Coding onto Wiki

### ISSUE THREAD

**Issue by Si-Shi** [Triangle-Modeling-and-Analytics/TRMG2#238]
Here is how Mike coded toll road for 2050 MTP scenario. Add these to the related wiki page. 
*
For the master_links layer delivered on Friday for the 2050 model run:
For the existing toll links that are open to traffic (TriEx and NC 540 from I-40 to NC 55), the tolls are applied at the specific links where the existing toll gantries are located.
For the section of NC540 under construction (from NC 55 east) and the managed lane projects, the tolls are applied on the individual toll links on a per mile basis using the same value that is on the open links (transponder $0.20/mile, non-transponder $0.39/mile).  This was done since it was unknown where the toll gantries would be and how much the toll would be on a particular section covered by a gantry.
For the Managed Lane projects, the current toll values were used (transponder $0.20/mile, non-transponder $0.39/mile). Note that because of the structure of the model (congestion and delay are calculated differently and this impacts how traffic is assigned to parallel facilities), this left a very low to 0 assignment on most of the managed lanes.  I did run a scenario that decreased the tolls on the managed lanes by half and it increased the assigned volumes to be comparable to the v62 volumes on the managed lanes, however, to be consistent with v62, the full toll is included in the final updated master_links layer.  At some point in the development of the 2055 MTP, these toll rates will need to be revisited.
*

**Comment by nitabhave** [comment]
edited content a bit and place here (wiki/7-Highway-Network-Management#toll-links)
