### ISSUE TITLE
Roadway capacity documentation added to the wiki

### ISSUE THREAD

**Issue by Si-Shi** [Triangle-Modeling-and-Analytics/TRMG2#239]
Per Leta's request, the wiki should reflect how G2 calculates capacity values, what's the source of the values, and any other specifics so that users will understand the G2 capacities. .

**Comment by nitabhave** [comment]
I added a small blurb to the wiki -- https://github.com/Triangle-Modeling-and-Analytics/TRMG2/wiki/4-Model-Inputs#unmodifiable-inputs
