### ISSUE TITLE
Master Links layer file contains p1-p4 Fields only

### ISSUE THREAD

**Issue by Flatiron87** [Triangle-Modeling-and-Analytics/TRMG2#280]
For the TRMG2v1.2 release, the master_links file only contains fields for projects p1-p4.  For TRMG2v1.1, there were fields for p1-p5.  While the p5 field may not have had any projects, it was still supposed to be included in the master_links layer for future coding purposes.

**Comment by lfhuntsinger** [comment]
The ‘NA’ seems to be used for many transit only links, but it’s not clear when ‘NA’ and ‘null’ should be used. If it is decided that ‘NA’ should be used for all links that do not have a NCDOTClass value then that is fine (need clarity on when to use).  In most cases, if a link is a drive link, then the NCDOTClass should be local.  Only Transit Only Links and non-drive links should probably be coded as ‘NA”.
