### ISSUE TITLE
MOVES Tool Edit for v1.2

### ISSUE THREAD

**Issue by Flatiron87** [Triangle-Modeling-and-Analytics/TRMG2#281]
I ran the MOVES converter in TRMG2v1.2 And found the following issues:
**Speed.csv file**
The field ‘DefaultFraction’ in the previous version was changed to ‘avgSpeedFraction_x’ in v1.2, however, it should just be ‘avgSpeedFraction’.  Also, it is unclear what the field ‘AvgSpeedFraction_y’ is for.  It is not needed by MOVES.  There is a ‘AvgSpeedFraction’ but most of the data in this filed is blank or zero.  Based on the last version the ‘avgSpeedFraction_x’ appears to be the correct value and the field name needs to be changed to avgSpeedFraction .
**Roadtype.csv file**
The field 'sourcetype' needs to be changed to ‘sourceTypeID

**Comment by Si-Shi** [comment]
Done
