### ISSUE TITLE
Scenario Creation - Missing Projects

### ISSUE THREAD

**Issue by Flatiron87** [Triangle-Modeling-and-Analytics/TRMG2#286]
If a project is listed in the 'RoadwayProjectList.csv' but not in the master_links layer, it should show a warning in the scenario creation step and create the missing projects file, and not crash.  This is the way it worked in TRMv62.  CAMPOs current project management system exports projects that may be complete in the base year (e.g. removed from the master_links layer and added to the base network layer), but still show up in their project list.  The option should be available for the scenario network to complete and allow the analyst to check the missing projects to determine whether to proceed.
![image](https://user-images.githubusercontent.com/71019177/230990500-27ba63e1-20e5-430e-a2e2-5c132ad21cb6.png)

**Comment by dkyleward** [comment]
Resolved by #299
