### ISSUE TITLE
Error trap for Scenario Builder

### ISSUE THREAD

**Issue by lfhuntsinger** [Triangle-Modeling-and-Analytics/TRMG2#289]
@dkyleward Create a new error trap for the scenario builder. Reference email from Friday, April 14, 2023.

**Comment by lfhuntsinger** [comment]
@dkyleward can you update me on the status of this? I think it is complete?

**Comment by lfhuntsinger** [comment]
@dkyleward  thank you for doing that. I think we decided to handle it in error trapping rather than scenario development.

**Comment by dkyleward** [comment]
Resolved by PR #299
