### ISSUE TITLE
Transit reporting summary files

### ISSUE THREAD

**Issue by Flatiron87** [Triangle-Modeling-and-Analytics/TRMG2#290]
Consider adding master route ID to the following output files.  This would allow for comparison of results between scenarios using the common master route ID:
boardings_and_alightings_by_period.csv
boardings_and_alightings_daily.csv
passenger_miles_and_hours.csv

Also, in the dev\ version (that Kyle sent out on 4/19) of the passenger_miles_and_hours.csv output file, the Agency is missing from the results output at the bottom of file. This seems to be the result of including a route ID from the master routes layer that is missing the Agency name.  Instead of ignoring the missing Agency name and continuing, it writes a null value for the Agency name for any routes that come after the one that is missing.
![image](https://user-images.githubusercontent.com/71019177/234973812-df804446-de04-40c3-993b-484a135974f2.png)

**Comment by Si-Shi** [comment]
https://github.com/Triangle-Modeling-and-Analytics/TRMG2/commit/0ed7d4077341d9a783b2d73ca6d38a54861cd2c9
