### ISSUE TITLE
Network Compare - Diff Tool

### ISSUE THREAD

**Issue by Flatiron87** [Triangle-Modeling-and-Analytics/TRMG2#291]
When run 'Diff Tool', save maps and master_links.dbd file with additional comparison fields to new folder either in the scenario folder or in the master\network folder and make it clear that it is the output from the 'Diff Tool'.  The master_link.dbd file with the difference fields should be written to a new master_links_difference.dbd file rather than to the original master_links file in the folder: "....\master\networks". The maps need to be automatically saved like the other tools that are run instead of just showing up on the screen.

**Comment by dkyleward** [comment]
This is a good idea. In addition, as mentioned at the user's forum, let's call the diff tool when we run the scenario comparison tool.

**Comment by Si-Shi** [comment]
@dkyleward is this doable in FY24?

**Comment by dkyleward** [comment]
The diff tool is now implemented in the scenario comparison tool on the tc10 branch and will be available in v2.0 @lfhuntsinger

**Comment by lfhuntsinger** [comment]
Fantastic! Thank you!!
