### ISSUE TITLE
Add field descriptions for transit fields on loaded output link layer

### ISSUE THREAD

**Issue by dkyleward** [Triangle-Modeling-and-Analytics/TRMG2#318]
@nitabhave can provide the field descriptions to use for these fields and I will add them to the model code.

For AB/BA_Walk_Flow (from Jim):

The issue here is that the specific fields AB_Walk_Flow and BA_Walk_Flow only exist in the transit flow tables which are drive access or drive egress. AB_Walk_Flow and BA_Walk_Flow do NOT exist in the walk access flow results tables. However, the other fields (AB/BA_Access_Walk_Flow, Egress_Walk_Flow, and Xfer_Walk_Flow) exist for ALL flow tables, both drive and walk. Thus, when you sum up all the fields across all the flow tables, this will cause the discrepancy. Access, egress, and xfer walk will be for both drive access/egress and walk access but walk_flow will ONLY be for drive access/egress, so they won’t necessary sum together. Walk_flow will either be equal to or LOWER than Access+Egress+Walk. If you look at the individual drive access/egress output flows, the access+egress+xfer there should sum to the walk_flow.

**Comment by nitabhave** [comment]
FIELD - Suggested Description

AB_TransitFlow - AB transit flow for all transit modes
BA_TransitFlow - AB transit flow for all transit modes
AB_NonTransitFlow - Access, transfer and egress components of transit trips (Access_Walk_Flow + Xfer_Walk_Flow + Egress_Walk_Flow +_Drive_Flow)
BA_NonTransitFlow - Access, transfer and egress components of transit trips (Access_Walk_Flow + Xfer_Walk_Flow + Egress_Walk_Flow +_Drive_Flow)
AB_Total_TransitFlow - All components of transit trips (TransitFlow + Access_Walk_Flow + Xfer_Walk_Flow + Egress_Walk_Flow + Drive_Flow)
BA_Total_TransitFlow - All components of transit trips (TransitFlow + Access_Walk_Flow + Xfer_Walk_Flow + Egress_Walk_Flow + Drive_Flow)
AB_Access_Walk_Flow - AB flow for transit passengers that walked to their initial transit stop
BA_Access_Walk_Flow - BA flow for transit passengers that walked to their initial transit stop
AB_Xfer_Walk_Flow - AB flow for transit passengers that walked from one transit stop to another on a given trip
BA_Xfer_Walk_Flow - BA flow for transit passengers that walked from one transit stop to another on a given trip
AB_Egress_Walk_Flow - AB flow for transit passengers that walked from a transit stop to their given destination
BA_Egress_Walk_Flow - BA flow for transit passengers that walked from a transit stop to their given destination
AB_Walk_Flow - AB walk flow ONLY for transit passengers that drove to transit
BA_Walk_Flow - BA walk flow ONLY for transit passengers that drove to transit
AB_Drive_Flow - AB drive flow ONLY for transit passengers that drove to transit
BA_Drive_Flow - BA drive flow ONLY for transit passengers that drove to transit

**Comment by Si-Shi** [comment]
@dkyleward is it something you can do in FY24?

**Comment by dkyleward** [comment]
Completed.
