### ISSUE TITLE
Update to project checking tool

### ISSUE THREAD

**Issue by Flatiron87** [Triangle-Modeling-and-Analytics/TRMG2#322]
Update current project checking tool to identify multiple projects on the same links and to identify missing projects in the master_links layer.

See link to description. https://docs.google.com/document/d/1rSfQ9GwF2osHn0iBr-FSrLp4OnErWZP5T7Y2zglGEBE/edit?usp=sharing

**Comment by Si-Shi** [comment]
@dkyleward is it something you can do in FY24? I think the first half of the issue can be resolved by adding the "overlapping" field.
