### ISSUE TITLE
Create summary maps for transit flow

### ISSUE THREAD

**Issue by dkyleward** [Triangle-Modeling-and-Analytics/TRMG2#327]
Not hard to create, but I don't think most end users realize the transit flow is being loaded on the link layer. Having a summary map is a nice way to highlight that.

In addition, we should add a transit diff map to the scenario comparison tool that quickly highlights changes in transit volumes.

**Comment by Si-Shi** [comment]
Is it doable in FY24? @dkyleward

**Comment by dkyleward** [comment]
Done!
