### ISSUE TITLE
Provide option to add tolls to pxID fields and not just base data

### ISSUE THREAD

**Issue by Si-Shi** [Triangle-Modeling-and-Analytics/TRMG2#352]
- Requested by: CAMPO-Mike
- Date: 12/2021
- Priority: L
- Additional details: See parking lot of questions 20

**Comment by dkyleward** [comment]
I agree 100% with Mike. I recommend closing this issue and modifying scenarios networks for tolling when needed.

**Comment by lfhuntsinger** [comment]
Agreed

**Comment by Flatiron87** [comment]
I've updated the wiki to reflect the results of this conversation.
Mike
