### ISSUE TITLE
Report that captures impact/influence to park & rides

### ISSUE THREAD

**Issue by Si-Shi** [Triangle-Modeling-and-Analytics/TRMG2#355]
- Requested by: CAMPO-Chris
- Date: 05/2022
- Priority: 
- Additional details: For example: run a post process that shows where (e.g. which TAZs) that park & ride driving trips are coming from as well as where those transit trips are going to (maybe that is two different reporting functions).

**Comment by Si-Shi** [comment]
Kyle will investigate to see what's possible

**Comment by dkyleward** [comment]
Done!

@lfhuntsinger @Si-Shi
