### ISSUE TITLE
RoadwayProjectList numerical value

### ISSUE THREAD

**Issue by leeklieman** [Triangle-Modeling-and-Analytics/TRMG2#364]
When the only project(s) in the RoadwayProjectList.csv file is a number, the Create Scenario step crashes.

**Comment by Si-Shi** [comment]
Is this a problem for v1.3 release or the dev branch model?

**Comment by leeklieman** [comment]
Gen 2v1.3


Lee Klieman, P.E., PTOE

Patriot Transportation Engineering, PLLC
***@***.******@***.***>
Office: 919.336.9342

**Comment by Flatiron87** [comment]
Hi
I was able to replicate your issue. The p1-p4 project fields are formatted as text. The scenario builder has issues with numbers as project IDs, especially, as you found out, if they occur first in the project list. My suggestion is that you always start any project that you create with a letter and then follow that with either numbers or letters. If you need to build a scenario with one of DCHC projects ( which are all numeric), then I would suggest that you always have a CAMPO project ( which always start with a character) as the first project in the highway project list.
Mike


Mike Bruff
Transportation Modeling Engineer
Capital Area MPO
1 Fenton Main Street, Suite 201
Cary, NC 27511
984-542-3601 (main)
984-542-3613 (direct)
campo-nc.us<https://www.campo-nc.us/>
***@***.******@***.***>


________________________________

**Comment by dkyleward** [comment]
I have corrected this and included it into dev via this PR: https://github.com/Triangle-Modeling-and-Analytics/TRMG2/pull/372

It will be included in v2.0. I'm not sure if there will be another 1.3 release (or when it will be), but we can cherry pick this fix into that release as well.
