### ISSUE TITLE
Custom scenario creation not an option on Scenario drop down menu

### ISSUE THREAD

**Issue by leeklieman** [Triangle-Modeling-and-Analytics/TRMG2#366]
According to the user's guide, the first step in performing a fixed OD assignment is to create a custom scenario.  The guidelines for this direct the user to add the scenario from the scenario drop down menu.  However, that is not an option I see in the drop down menu.  (I only see the as-delivered scenario years, plus the 'Design or Edit Model' option).

**Comment by Flatiron87** [comment]
In the model scenario folder, create a new scenario (say 2050_EvaluateUS70) and copy the 2050 roadway and transit project lists (RoadwayProjectList.csv and  TransitProjectList.csv) to this folder. In the flowchart add a new scenario and update the parameters for it.

Select the new scenario in the scenario drop down box and then run the create scenario tool under the TRMG2 tab.

After your scenario is created, go to ….\scenarios\2050_EvaluateUS70\input\networks\ scenario_links.dbd and make the change in the project that you want to evaluate.

The next step is to run the ‘Fixed OD Assignment’. It will take about 4 hours (vs 14-16 hours for a full 2050 model run).  Note that the fixed OD tool is not intended to evaluate changes in land use or the addition of major new location projects that would impact the original trip assignment distribution.

Mike

Mike Bruff
Transportation Modeling Engineer
Capital Area MPO
1 Fenton Main Street, Suite 201
Cary, NC 27511
984-542-3601 (main)
984-542-3613 (direct)
campo-nc.us<https://www.campo-nc.us/>
***@***.******@***.***>


From: leeklieman ***@***.***>
Sent: Thursday, February 29, 2024 11:47 AM
To: Triangle-Modeling-and-Analytics/TRMG2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Triangle-Modeling-and-Analytics/TRMG2] Custom scenario creation not an option on Scenario drop down menu (Issue #366)


According to the user's guide, the first step in performing a fixed OD assignment is to create a custom scenario. The guidelines for this direct the user to add the scenario from the scenario drop down menu. However, that is not an option I see in the drop down menu. (I only see the as-delivered scenario years, plus the 'Design or Edit Model' option).
