### ISSUE TITLE
Congested VMT Summary Files Discrepancy

### ISSUE THREAD

**Issue by Flatiron87** [Triangle-Modeling-and-Analytics/TRMG2#375]
In the summary file Congested_VMT_by_MPO, when you add the congested VMT by period to get a daily congested VMT, you get 5,072,996.  However, in the VMT_Delay_by_MPO, the Total_CgVMT_Daily is 1,012,660.  In both files, the Total VMT is correct.
![image](https://github.com/Triangle-Modeling-and-Analytics/TRMG2/assets/71019177/6a4b3e0b-3500-46f2-a2af-8dae34a72851)

**Comment by dkyleward** [comment]
@Si-Shi and @lfhuntsinger I've reviewed this, and we just need a decision on what the cutoff should be. My (older) macro used 0.75, which is what I use across multiple models to designate a link as congestion. The second macro is Si's, which uses 1.0. My recommendation is to use .75 in both, however either is fine depending on what the region wants. We just want them to be the same.

**Comment by Si-Shi** [comment]
Thanks for bringing this up! We will discuss it at the tech team meeting
and let the team decide.

**Comment by Flatiron87** [comment]
My suggestion is to use
.75 across the board. As long as it is documented and consistent.
Mike

**Comment by Flatiron87** [comment]
Can we resolve this for v2. We agree on the .75 cutoff.  Need to go into the script (see image) for the following output files: VMT_Delay_by_MPO.csv, VMT_Delay_by_County.csv, VMT_Delay_by_HCMType.csv, VMT_Delay_by_AreaType.csv, VMT_Delay_by_HCMType_by_County.csv and change the calculation for CgVMT in each of these to the >.75 cutoff. This will then match the CgVMT on the following: Congested_VMT_by_MPO.csv, Congested_VMT_by_County.csv. ****Location in script. Change 1.0 to ,75. 
![image](https://github.com/user-attachments/assets/154041ad-bec3-4e13-aa88-a0c98ae43663)

**Comment by Flatiron87** [comment]
I tried changing the voc>1 to voc>0.75 in the v2 summaries script to see if the results from the VMT_Delay summary files would match the results in the Congested_VMT files. The congested VMT in the  Congested_VMT files is 4,434,379, however, the congested VMT in the VMT_Delay files is 9,041,508.  The previous of this with voc>1 was 765,573.  I had expected them to match. The files are: (Congested_VMT_by_MPO.csv, Congested_VMT_by_County.csv) vs. (VMT_Delay_by_MPO.csv, VMT_Delay_by_County.csv, VMT_Delay_by_HCMType.csv, VMT_Delay_by_AreaType.csv, VMT_Delay_by_HCMType_by_County.csv).

**Comment by Si-Shi** [comment]
https://github.com/Triangle-Modeling-and-Analytics/TRMG2/commit/bea81167724a87ba82dde1735b17e15629b63255
