### ISSUE TITLE
Equity Summary File skipping TAZs

### ISSUE THREAD

**Issue by Flatiron87** [Triangle-Modeling-and-Analytics/TRMG2#376]
When the taz_designation.csv file is created in the summary equity script, if a TAZ has zero HHs or zero HH_pop, it skips that TAZ in the output file.  This creates an issue when you try to combine the TAZ file with the taz_designation file.  It is requested that when a TAZ has zero HHs or zero HH_pop that the TAZ be included in the taz_designation.csv. It is also requested that the MPO and county be included in the taz_designation.csv file. 
See figure below for an example of the issue.  Note TAZ 81. It is in the scenario_taz file and the scenario_se files, but not in the taz_designation.csv because the TAZ has zero HHs or zero HH_pop.
![image](https://github.com/Triangle-Modeling-and-Analytics/TRMG2/assets/71019177/ac9855a2-25e9-42ff-b6c6-eb4ae92dc9c5)

**Comment by dkyleward** [comment]
> This creates an issue when you try to combine the TAZ file with the taz_designation file

If you join the taz_designation file to the TAZ layer, you should just get an empty row for those missing TAZs, but you can still summarize and work with it. Is that good enough?
