### ISSUE TITLE
Speed Reduction Output Maps

### ISSUE THREAD

**Issue by ggermainedaniel** [Triangle-Modeling-and-Analytics/TRMG2#384]
Speed Reduction Output maps lose symbology when map view is expanded or if the geography is panned. The Time of Day flow attribute by also seems to be matched incorrectly with the map output (ie...the PM Speed Reduction map geography does not have the AB/BA Flow_PM attribute referenced in the code instead it has the AB/BA Flow_AM attribute, this could be generating the error described above).

**Comment by dkyleward** [comment]
I can't reproduce this issue. My map symbology redraws correctly when zooming/panning/etc. Also, the PM map is referencing the right field:

<img width="917" alt="image" src="https://github.com/Triangle-Modeling-and-Analytics/TRMG2/assets/10221750/32d30bb2-a4d1-4897-b1c3-86d9f49f100d">

**Comment by ggermainedaniel** [comment]
I am getting this behavior now with other maps in directory. Below is a screenshot of an error message received when attempting to zoom in on a Daily LOS D map. It opens correctly however any attempt to expand the window and resize the network results in this error.

![image](https://github.com/Triangle-Modeling-and-Analytics/TRMG2/assets/37350807/bfef7bc2-e3dd-4cf8-8ad1-360f572aa1df)

**Comment by ggermainedaniel** [comment]
Ahh nevermind, the attribute field is missing pertinent columns due to previous edits I made.
