### ISSUE TITLE
Draft fields to export for Shapefile

### ISSUE THREAD

**Issue by tpadgett3** [Triangle-Modeling-and-Analytics/TRMG2#389]
See attached spreadsheet with fields.  My opinions, grey fields should not be exported, blue fields might be useful but may be okay to omit as well.  White fields need to be exported.
[FieldsForShapefileExport.xlsx](https://github.com/Triangle-Modeling-and-Analytics/TRMG2/files/15324951/FieldsForShapefileExport.xlsx)

**Comment by dkyleward** [comment]
@tpadgett3 I've got the code written to export this, but the output field names being limited by the shapefile format is pretty brutal. Not being able to see which period a field belongs to makes it useless.

<img width="729" alt="image" src="https://github.com/Triangle-Modeling-and-Analytics/TRMG2/assets/10221750/3bc76224-5ad5-4274-b7dc-cb2c92dd7597">

Is this helpful at all? If you explain why you need a shapefile, perhaps I can come up with some other solution?

One idea would be to export the geography and then write the attributes to a CSV file that you could then join to the shapefile renaming the 2-3 fields you need on the fly. Of course, all of this is possible to do manually, so maybe we don't need this built into the model to happen every time?

CC'ing @lfhuntsinger

**Comment by dkyleward** [comment]
One other thought: in case you don't know, with a table open in TransCAD, you can go to Dataview -> Fields -> show/hide and then quickly search for the few fields you need. Then, if you export that manually, you only get those fields as output.

**Comment by Flatiron87** [comment]
@dkyleward @lfhuntsinger A shapefile is typically needed by external partners who would like to analyze data in AGOL.  We also need shape files or geodatabases for CAMPO prioritization tool.  We currently have two workarounds. The first is what you mentioned: export and then join to a csv file.  The second is that that we export to a json, however, that requires the creation of a separate ID field.  For general export to .xlsx we use the Dataview -> Fields -> show/hide to select on the fields that we need.  We could use this for the .shp file export, however, it still truncates the field names.

**Comment by dkyleward** [comment]
@tpadgett3 and @Flatiron87 I'm currently investigating exporting an ESRI geodatabase without field name restrictions. Is a geodatabase/feature class helpful or does it need to be a shapefile? If it needs a shapefile, then I'd ask @tpadgett3 to update your excel workbook to include the new names. They  need to be <10 characters and all letters will wind up capitalized.

**Comment by Flatiron87** [comment]
@tpadgett3 @dkyleward @lfhuntsinger An ESRI geodatabase file would be good if TC can export to it with no issues.  We can modify our new prioritization tool to use it and I think our other partners could use that as well.  I will let others chime in, but, at this point, I would be against a wholesale renaming of G2 model fields just to accommodate an AGOL limitation.

**Comment by dkyleward** [comment]
Done!
