### ISSUE TITLE
Consider loosening default feedback convergence

### ISSUE THREAD

**Issue by dkyleward** [Triangle-Modeling-and-Analytics/TRMG2#390]
The feedback mechanism for this model compares skim matrices from consecutive iterations and checks the %RMSE to determine convergence. The current parameters are:

Max Iterations: 5
Target Gap: 0.1%

In my latest base year run, here is the AM assignment report:

<img width="109" alt="image" src="https://github.com/Triangle-Modeling-and-Analytics/TRMG2/assets/10221750/ecfda505-eddf-4693-8972-579d2a4a8722">

If we moved to 1% gap instead of .1%, the AM period would only run twice instead of 4 times. This would be a sizable reduction in run times without giving up too much on the tightness. Recall that the model is using warm-start link times which is why it doesn't need to feedback as many times.

On a related note, the various updates we've done to date in v2 (including moving to TC10 and others) are why the base year is feeding back rather than finishing after a single iteration. Before creating a new release, we always update the warm start times.

**Comment by lfhuntsinger** [comment]
@dkyleward thank you for your research into this matter. Modificaiton of the closure criteria will be discussed and decided at the June 5 Tech Team meeting.

**Comment by lfhuntsinger** [comment]
We have decided not to change this in the model, but rather to let folks do it for specific scenarios if they so choose.
