### ISSUE TITLE
Error in mode share summary table

### ISSUE THREAD

**Issue by Flatiron87** [Triangle-Modeling-and-Analytics/TRMG2#392]
The following table (overall_mode_shares_bytaz.bin) sums up the origin and destination trips for each TAZ including the od_veh_trips_PM_PKHR.mtx file (see .rsc snippet below).  This .mtx should be excluded since it is already accounted for in the od_veh_trips_PM.mtx matrix.  This results in too many origins and destinations by TAZ.  The description should also note that these are the sum of the trip origins and trip destinations for each TAZ. Other summary tools should be reviewed to make sure this same over counitng is not occurring.

![image](https://github.com/Triangle-Modeling-and-Analytics/TRMG2/assets/71019177/75905098-2a4e-40a5-b237-3bc0c03dc95b)

![image](https://github.com/Triangle-Modeling-and-Analytics/TRMG2/assets/71019177/8c0d9b87-9a58-4c01-95cc-81ab19cbc49f)

**Comment by Flatiron87** [comment]
As a follow-up, this file and the overall_mode_shares_bycounty.bin include the  productions at the external stations. Should these be excluded or if included, should a county name be assigned to them? Does 'auto' mode in this table include cv, sut and mut? 
![image](https://github.com/Triangle-Modeling-and-Analytics/TRMG2/assets/71019177/912e6f24-e6ef-4e60-a99f-c307e9c2c069)

**Comment by dkyleward** [comment]
First part fixed in commit fde5bd19ea37043edbe67b16413be3f54b9d91ae

For the second part, yes, they include CV/SUT/MUT. This is because what is being summarized is the entire highway assignment matrix. Also, if you want that null record to be replaced by "externals" let me know, but I'm going to mark this closed for now.
