### ISSUE TITLE
Delay for CV, SUT and MUT not calculating correctly

### ISSUE THREAD

**Issue by Flatiron87** [Triangle-Modeling-and-Analytics/TRMG2#427]
It appears that the CV, MUT and SUT delay values in the scenario link file is showing minutes instead of hours. This is affecting several of the output files including the performance csv files and the VMT delay summary. See comparison in the attached.
[master_links_chkDelay.xlsx](https://github.com/user-attachments/files/17464010/master_links_chkDelay.xlsx)

**Comment by dkyleward** [comment]
CC @lfhuntsinger 

Hey Mike. Thanks for reporting this. The problem looks like I was just setting the wrong vector (flow) instead of delay. Here's the fix, which is now merged into dev for the next model:

![image](https://github.com/user-attachments/assets/d2dbab6e-20d7-41ed-ae66-09cba335ff35)

**Comment by lfhuntsinger** [comment]
Thank you Kyle!
