### ISSUE TITLE
CoC Tool Issue with "Number of Categories" option

### ISSUE THREAD

**Issue by jkolling2** [Triangle-Modeling-and-Analytics/TRMG2#437]
When I run the tool with '1 or more categories' I get results that look like they are the results for '0 or more categories mpo CD' and when I run the tool for '2 or more categories mpo CD' I get results that look like they are the results for '1 or more categories mpo CD.'

The '2 or more categories mpo CD' results also match the results I get when I do the "selected categories" option instead and select all categories and the "or" option. 

For example, when I run it with the '1 or more categories mpo CD' option, the AM_per_capita_metrics.csv says CoC_TAZs_in_Geo = 2783, which is the total number of TAZs in DCHC MPO + CAMPO (and thus would make sense if I had selected '0 or more categories mpo CD'

FYI there are no CoC TAZs that are not in DCHC MPO or CAMPO.

**Comment by dkyleward** [comment]
Got this one fixed.
