### ISSUE TITLE
Reporting mode choice results

### ISSUE THREAD

**Issue by lfhuntsinger** [Triangle-Modeling-and-Analytics/TRMG2#82]
Can we include a way to report mode share summaries for zones that have transit access in additon to as a region? For example, transit share for the entire region is tiny. When transit improvements are made, the regional needle barely moves. It would be nice to see a mode summary for every model run that was just for zones that have transit access (recognizing that the zones that have transit access can change from scenario to scenario).

**Comment by Si-Shi** [comment]
@dkyleward please add this to your to-do list for FY24. We would like to have this in both v1.3 series and v2.

**Comment by lfhuntsinger** [comment]
Other tools do something very similar to this. The actual implementation of this by access mode and time period would be a heavy lift. There does not seem to be a demand for it. Close the issue.
